# Build stage
FROM node:16
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD [ "ls" ]
CMD ["npm", "start"]

# RUN npm run build
# # Production stage
# FROM nginx:stable
# COPY --from=build-stage /app/build /usr/share/nginx/html
# EXPOSE 3000
# CMD ["nginx", "-g", "daemon off;"]