# FROM node

# WORKDIR /work/waiton_todolist

# COPY package*.json ./

# RUN npm install

# # COPY 
# COPY ./ ./

# EXPOSE 3000

# CMD ["npm", "start"]

# Build stage
FROM node:16 as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Production stage
FROM nginx:stable
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]